name: CI

on:
    pull_request:
        branches:
            - main

env:
    SOLUTION_PATH: dotnet/flx.SILQ.sln

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x
            - name: Restore dependencies
              run: dotnet restore ${{ env.SOLUTION_PATH }}
            - name: Build
              run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
            - name: Test
              run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-build --verbosity normal
            - name: Publish
              run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release --no-build --output ./artifact/
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                path: ./artifact/